version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - '80:80'
      - '3000:3000'
    environment:
      NODE_ENV: production
      PORT: 3000
      API_URL: http://localhost
    volumes:
      - ../src:/app/src
      - ../public:/app/public
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost/api/health']
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  # Alternative: Development setup with separate services
  dev:
    image: node:20-alpine
    working_dir: /app
    command: npm run dev
    ports:
      - '3001:3000'
    environment:
      NODE_ENV: development
    volumes:
      - ..:/app
      - /app/node_modules
    profiles:
      - dev
